# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy application files
COPY pyproject.toml ./
COPY README.md ./
COPY main.py ./

# Install dependencies
RUN pip install --no-cache-dir httpx "mcp[cli]>=1.3.0"

# Expose any ports if needed (not required for stdio transport)

CMD ["python", "main.py"]
