# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use official Python 3.11 image
FROM python:3.11-slim

# Set environment variables
# ENV PYTHONDONTWRITEBYTECODE=1 \
#     PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Install uv (recommended via pipx)
RUN pip install --no-cache-dir pipx && \
    pipx install uv && \
    pipx ensurepath

# Ensure uv is available in PATH
ENV PATH="/root/.local/bin:$PATH"

# Copy pyproject.toml and lock file (if available)
COPY pyproject.toml /app/

# Install dependencies with uv
RUN uv pip install -r <(uv pip compile pyproject.toml)

# Copy the rest of the application code
COPY . /app

# Run the app
CMD ["python", "main.py"]